### ISSUE TITLE
Missing config in documentation for service accounts and S3 backend

### ISSUE THREAD

**Issue by gviot** [chartmuseum/charts#19]
This is from the documentation at https://github.com/chartmuseum/charts/tree/main/src/chartmuseum#permissions-grant-with-iam-roles-for-service-accounts
> permissions grant with IAM Roles for Service Accounts
> 
> For Amazon EKS clusters, access can be provided with a service account using IAM Roles for Service Accounts.
> 
> Specify custom.yaml with such values
> 
> ```
> env:
>   open:
>     STORAGE: amazon
>     STORAGE_AMAZON_BUCKET: my-s3-bucket
>     STORAGE_AMAZON_PREFIX:
>     STORAGE_AMAZON_REGION: us-east-1
> serviceAccount:
>   create: true
>   annotations:
>     eks.amazonaws.com/role-arn: "arn:aws:iam::{aws account ID}:role/{assumed role name}"
> ```

the provided value file doesn't work, using it as it is now will use the node's role for S3 access instead of the service account's role, and resulted in access denied for me.
This should be added to environment variables: AWS_SDK_LOAD_CONFIG: true

```
env:
  open:
    AWS_SDK_LOAD_CONFIG: true
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: my-s3-bucket
    STORAGE_AMAZON_PREFIX:
    STORAGE_AMAZON_REGION: us-east-1
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{aws account ID}:role/{assumed role name}"
```
