### ISSUE TITLE
CHART_URL not working properly

### ISSUE THREAD

**Issue by nicolasespiau** [chartmuseum/charts#47]
Hey folks,

I've deployed chartmuseum using the chart, and I've set CHART_URL like this:
```yaml
env:
  open:
    CHART_URL: "http://helm.mycompany.com"
```

But when I fetch a package I get a 404 not found error with this message:  
```bash
Error: failed to fetch http://helm.mycompany.com/helm.mycompany.com/charts/mycompany-app-1.1.tgz : 404 Not Found
```

As you can see the base url is repeated.

Here is the index.yaml:  
```yaml
apiVersion: v1
entries:
  mycompany-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-12T10:50:24.966478774Z"
    description: A Helm chart for Kubernetes
    digest: **DIGEST**
    name: mycompany-app
    type: application
    urls:
    - helm.mycompany.com/charts/mycompany-app-1.1.tgz
    version: "1.1"
generated: "2022-08-12T10:50:25Z"
serverInfo: {}
```

I wonder why the `http` is removed from env var.  
I deployed the chart once with `CHART_URL: "helm.mycompany.com"` but I updated then uninstalled and reinstalled it with the proper CHART_URL but I still can't install or fetch because of this base domaine repetition.

Any clues?
