### ISSUE TITLE
Chart-museum chart doesn't comply with 'restricted' Pod Security Standard

### ISSUE THREAD

**Issue by derbeneviv** [chartmuseum/charts#59]
Current 'restricted' kubernetes pod policy standarts (https://kubernetes.io/docs/concepts/security/pod-security-standards/) require the following to be set up:
```
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

Current helm chart contains setting for runAsNonRoot but not for seccompProfile

Suggestion:
chart-museum should contain options to specify non-default seccompProfile.   
Ideally, fully custom securityContext should be possible 

I can do a pullrequest
